---

status:
  port: 18888
  user: gorouter
  pass: "c1oudc0w"


nats:

  - host: 192.168.64.142
    port: 4222
    user: nats
    pass: "c1oudc0w"


logging:
  file: /var/vcap/sys/log/gorouter/gorouter.log
  
  syslog: vcap.gorouter
  
  level: info


loggregatorConfig:
  url: 192.168.64.142:3456
  shared_secret: c1oudc0w


port: 8888
index: 0
pidfile: /var/vcap/sys/run/gorouter/gorouter.pid
go_max_procs: 8
trace_key: 22
access_log: /var/vcap/sys/log/gorouter/access.log

publish_start_message_interval: 30
prune_stale_droplets_interval: 30
droplet_stale_threshold: 120
publish_active_apps_interval: 0 # 0 means disabled

endpoint_timeout: 300
