newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: ''
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 1

#
# Agent Configuration, describe your nginx instances here
#
agents:
  nginx_status_agent:
    -
      instance_name: 'CC Nginx (development)'
      status_url: http://localhost:9022/nginx_status
