---
server:
  unix_domain_permissions: 0777
  unix_domain_path: /var/vcap/data/warden/warden.sock
  container_klass: Warden::Container::Linux
  container_rootfs_path: /var/vcap/packages/rootfs_lucid64
  container_depot_path: /var/vcap/data/warden/depot
  pidfile: /var/vcap/sys/run/warden/warden.pid
  quota:
    disk_quota_enabled: true

logging:
  file: /var/vcap/sys/log/warden/warden.log
  level: debug
  

health_check_server:
  port: 2345

network:
  pool_start_address: 10.254.0.0
  pool_size: 256
  
  

  # Interface MTU size
  # (for OpenStack use 1454 to avoid problems with rubygems with GRE tunneling)
  mtu: 1500

user:
  pool_start_uid: 20000
  pool_size: 256
